import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";
import NavBar from "./NavBar";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});
// import AuthProvider from "./Provider";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				{/* <AuthProvider> */}
				{/* <Theme accentColor='blue' radius='none' scaling='95%'> */}
				<NavBar />
				<main>{children}</main>
				{/* <ThemePanel /> */}
				{/* </Theme> */}
				{/* </AuthProvider> */}
			</body>
			{/* <ThemePanel /> */}
		</html>
	);
}

