import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";
import NavBar from "./NavBar";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import AuthProvider from "./Provider";
import QueryClientProvider from "./query-provider";
import { currentRole } from "@/lib/auth";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./theme-provider";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryClientProvider>
			<AuthProvider>
				<html lang='en' suppressHydrationWarning>
					<body
						className={cn(
							"bg-background font-sans antialiased min-h-screen",
							fontSans.variable
						)}>
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							disableTransitionOnChange>
							<main className='flex flex-col w-full'>
								<NavBar />
								<div className='flex-1'>{children}</div>
							</main>
							{/* <ThemePanel /> */}
							{/* </Theme> */}
							<Toaster />
						</ThemeProvider>
					</body>
					{/* <ThemePanel /> */}
				</html>
			</AuthProvider>
		</QueryClientProvider>
	);
}
